### PR TITLE
Add AreoMode setting can use HUD without Areo

### PR DESCRIPTION
**Pull request by flier268**
My OS is ubuntu 16.04 , I can play POE on wine,and then try the HUD.
I fount HUD need Areo ,but wine didn't have Areo( i did not found)
so i try to remove Areo request.

setting.json -> menu -> "AreoMode": false,

//I am a beginner,so the code is not beautiful,and maybe have some bug
I remove some features,because i have no power to do it.**I need some help.**

Image:
http://imgur.com/a/3WsdJ

### CODE REVIEW

**Comment by DetectiveSquirrel** [comment]
Aero is required to draw a transparent window and overlay it, is there any transparent features or examples in ubuntu?

**Comment by zaafar** [comment]
I think he only want preload alerts,

**Comment by flier268** [comment]
I think that the useful feature is vaal area,preload alert,monster alert,dps calculater,health bar,Advenced tooltip

Inventory preview : i don't know how to use it,i never see that show any different with null
minimap , item alert : usually invalid on GareanTW,so I give up to use it

so ,if i change it, I just lose health bar.(i think)

**Comment by TehCheat** [comment]
Why not just dual boot to Windows to use a tool designed to be run in Windows for a game designed to be played in Windows?  HUD isn't intended to be run in Wine or in linux.  This issue is like complaining that a dog collar isn't working on a rabbit.  I'm closing the issue.

**Pull request closed without merging**
