### PR TITLE
New niko

### PR DESCRIPTION
**Pull request by Lachrymatory**
new niko

### CODE REVIEW

**Comment by zaafar** [comment]
Please remove the old niko if any.

**Comment by zaafar** [comment]
{"Metadata/NPC/League/DelveMiner", new PreloadConfigLine {Text = "Niko the Mad", FastColor = () => Settings.MasterNiko }},

**Comment by zaafar** [comment]
Or just update the old niko

**Comment by Lachrymatory** [comment]
The hardcoded masters (except Zana) haven't been working since the start of betrayal. I don't know how you want to handle that so I'll leave it to people with more access. Below should cover current masters, Zana's fine as mentioned.

```
# MASTERS
Metadata/Monsters/Masters/Einhar; Einhar, Beastmaster; ff64ffff
Metadata/NPC/League/Delve/DelveMinerWildVein; Niko, Master of the Depths; ff64ffff
Metadata/NPC/League/Delve/DelveMinerWildChest; Niko, Master of the Depths; ff64ffff
Metadata/NPC/League/Incursion/TreasureHunterWild; Alva, Master Explorer; ff64ffff 
```

**Comment by zaafar** [comment]
I will add it. Thx.

**Pull request closed without merging**
