### PR TITLE
new detecting method

### PR DESCRIPTION
**Pull request by vmv**
- It is finding all chests without the need to move from waypoint. Test it before patching, i did and the result are pretty good. 
Dunno if there is any performance impact tho, but you should know better ...:)

Ty,

### CODE REVIEW

**Comment by TehCheat** [comment]
I'm confused what you're trying to accomplish here.  I put that safeguard in just in case no specific chest is loaded but the PerandusChest.ao file is loaded (which means there is one).  I can't test it consistently, because it doesn't happen to me consistently.  I think I've seen it once in several hundreds (if not thousands) of instances.  I have a feeling the people that see it more often are on 32-bit PCs.

**Comment by vmv** [comment]
detect2

I'm using both methods simultaneously, and whenever there is an "unknown"...the new method knows already what type of chest it is.
Dunno, it works fine for me.

**Comment by vmv** [comment]
Another concern is this: 

strongbox

As you can see, there is no Jeweler's strongbox and it will appear later if you go away in map or move around.

**Comment by TehCheat** [comment]
The problem I have is I saw it *once* where it showed guardians and no chest using the new method, so I'd rather not remove it in case other run into the same thing.

**Comment by vmv** [comment]
Yep, safety first :).

**Pull request closed without merging**
