### PR TITLE
Some little fixes

### PR DESCRIPTION
**Pull request by Qvin0000**

### CODE REVIEW

**Comment by TehCheat** [comment]
If we have to add a delay after an area has changed, I feel like we're finding out if we're in a new area the wrong way. Didn't need that before, which tells IsGameLoading() is less accurate than the old way. Am I wrong?

**Comment by zaafar** [comment]
I think we are using IsGameLoading wrong.
The way it should work is,

If ( IsGameLoading == 1 )
    Donot return; sleep here; whatever;
else return False;

Basically background logic is this

If IsGameLoading changes from 0 to 1 it means game started loading. We need to wait till it changes back to 0 from 1. Only then we are 100% sure that everything is loaded.


So change the function accordingly and we wouldn’t ever need a single sleep for IsGameLoading things.

**Comment by Qvin0000** [comment]
In 3.1.0  IsGameLoading changed or we read not last field.
Data have more than 1 loading trigger and i think we need try read field Loaded.
I dont know where they now in memory, soon i try find him. 
But not sure this help us. 
Because for me preload works fine without delay, but my friend often told me about needed press F5 for actually data and when i added delay,  problem solved for him. He playing from HHD, maybe this problem with slow load from disk.

> Only then we are 100% sure that everything is loaded.
Game have field when loaded, but i not sure what mean this field.
Maybe this field only for main data what needs for rendering.

**Comment by TehCheat** [comment]
I run into the same problem with my private maphack. I switch areas, the area hash changes, I put it in a loop waiting for the IsLoading to change, once it's no longer loading, I turn the map hack on, but if I don't put a delay in, it won't work.  And the needed delay varies greatly by area, and by league (apparently standard league has lower priority when it comes to creating instances and needs a bigger delay). A large area needs a longer delay than a small area.

I believe there's a load screen UI Element, I'll have to dig up where it is, but I think that would be ideal. When it has IsVisible set to 1, the load screen is up, when it's set to 0, the load screen is no longer up. That might be perfect.

**Comment by zaafar** [comment]
As far as I know my maphack is using this isLoadingGame variable and correctly reloading the maphack on area change. So are you talking about another variable which we are missing?? Cuz this one is correctly turning into 1 and 0 on loading screen.

If that is the case i.e finding new variable ( on loaded / is everything loaded / etc etc ) I think it’s better to move to the old way. What was it based on? Area change counter? If I am not wrong.

**Comment by TehCheat** [comment]
I see the IsGameLoading variable change to a 1, but it changes to a 0 way too early for a lot of things (loaded assets, map, etc.). I don't really want to discuss why it doesn't work with my maphack, because I don't want it public, but that variable isn't terribly useful which is exactly why we need a delay on top of it.

We should discuss this in the contributors and above section on discord.

**Pull request merged**
