### PR TITLE
Added my known izaro phases and how to get extra keys

### PR DESCRIPTION
**Pull request by DetectiveSquirrel**

### CODE REVIEW

**Comment by TehCheat** [comment]
I like this.  This is a nice quality of life change.

Mind added commented out ones (we'll need to get the proper paths) for the following?
"Conduits; Let activate"
"Essences; Don't kill" (is this the one you labeled Golems?)
"Gargoyles; Don't kill"
"Idols; Let activate"
"Lieutenants; Don't kill"

**Comment by DetectiveSquirrel** [comment]
Uhh yeah i labeled essences golems for some reason, im adding them as i see them in harb uber lab

**Comment by TehCheat** [comment]
Merciless lab has gargoyles today.  Normal lab has Conduits.  I'll try to run them later and remember to do a loaded file dump so we can get those figured out.

**Comment by DetectiveSquirrel** [comment]
Just looked at conduits, they wernt loaded into preload tho so im not sure

**Comment by DetectiveSquirrel** [comment]
Ohh i get what you mean about adding but having commented out now sigh... pushing

**Comment by TehCheat** [comment]
Very nice.  We'll figure out the remaining ones in the coming days and update it as we can.  For now it is very useful, especially to those that don't run lab often and want max keys.

**Comment by DetectiveSquirrel** [comment]
Cheers, im starting to get more proficient in how PoEHUD works so im starting to add lots of random stuff, some make sense some dont

**Comment by zaafar** [comment]
Good work man!

**Pull request merged**
