### PR TITLE
Sorted Preload Strings

### PR DESCRIPTION
**Pull request by DetectiveSquirrel**
Preloads will be sorted then searched to be more consistant in how each
preload is shown

### CODE REVIEW

**Comment by TehCheat** [comment]
Do you have an ownedcore account?

**Comment by DetectiveSquirrel** [comment]
Yes im Sithylis :)

**Comment by zaafar** [comment]
@DetectiveSquirrel why sort it???? What's the benifit. ( for info only )

**Comment by DetectiveSquirrel** [comment]
So X is preload is always written before X preload and not in the orders the game loads them as, spirits will be with spirits and so on. It's just a cleaner display really.

**Pull request merged**
