### PR TITLE
Fix legion hp bar spam

### PR DESCRIPTION
**Pull request by DetectiveSquirrel**
Should now hide legion hp bars while they are stuck in a frozen state if monolith is not active
will show hp bars once monolith is active and they have not yet been released
will remove the hp bar if they have been released and will spawn once the time runs out.

### CODE REVIEW

**Comment by TehCheat** [comment]
Do we want to do the same for map icons? I would think so.

**Comment by Eric5766** [comment]
It's fairly useful to be able to see the Legion mobs before they spawn eg the minimap icons let you see where all the chests are before activating.

**Comment by TehCheat** [comment]
Well I think there are other plans for that, i.e. marking important chests/mobs, but the spam of everything currently is annoying, to say the least.

**Comment by DetectiveSquirrel** [comment]
So will this be merged?
the map icons are better after Stridemanns update to make IsHidden mobs use a transparent icon which REALLY helps with the clutter, ive been using those icons for the last day and it feels really nice.

**Comment by TehCheat** [comment]
I'm questioning if this is the best place for it. If we track legion mobs at a higher level, more plugins will have access to it.

**Pull request merged**
