### PR TITLE
Changed preload_alerts.txt

### PR DESCRIPTION
**Pull request by amazo197**

### CODE REVIEW

**Comment by vmv** [comment]
What are this 1- 40 chests for ? They are always inside after killing Izaro, not on the other areas...

**Comment by TehCheat** [comment]
I'm curious if those chests can be matched to their contents.  If so, that'd be a way to make some serious bank.  Like if IzaroChest37 is Divination cards you'd know to open it, etc.

**Comment by DetectiveSquirrel** [comment]
I mean, having 40 different chests?
Dont forget there was that one day where a certain chest was a 100% unique item drop so it could maybe be the case

**Comment by zaafar** [comment]
Woh, that would be epic!!!!
Also if we can point to which one of them is which, rather than showing on the preload only.

**Comment by zaafar** [comment]
Merge it, I wanna try this!!

**Comment by TehCheat** [comment]
Perhaps I should write a private tool... I just moused over all of them after a run and they each had different Paths (as HUD calls id).  I recorded the contents of the ones I opened.  I'll try and see if I notice a trend.

**Comment by TehCheat** [comment]
I'm not going to merge it as-is, because it'd be stupid to throw 7 chests names that mean very little into the preloads for an Izaro fight.  Let's figure out which ones are which and then I'll write a private plugin to identify the expensive ones.  :p

**Comment by DetectiveSquirrel** [comment]
How did you get what you were hovering over?

**Comment by zaafar** [comment]
I agree! a private plugin would be nice!
@DetectiveSquirrel  u can use following plugin for that
http://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/627025-poehud-plugin-objectsdebugplugin-developers.html

**Comment by TehCheat** [comment]
The item on ground hover offset is broken on HUD, but I grabbed the right offset and used another program to monitor the entity that was being hovered over.

**Comment by TehCheat** [comment]
So this is working and is incredibly game breaking.  I'd suggest keeping it quiet.  Don't publicize anything regarding this.  I'm gonna create a plugin for HUD and I'll share it with you guys but it's staying private beyond that, unless someone wants to sell a kidney to get their hands on it.  I'll be deleting everything regarding this shortly.

**Comment by amazo197** [comment]
Tehcheat can u close or delete this pull request because iam failed a little bit and dont want to public it

**Pull request closed without merging**
